version: '2.2'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    env_file:
      - docker-compose.env
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  cron:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    command: ["/bin/sh", "-c", "env /bin/bash -o posix -c 'export -p' > /etc/cron.d/project_env.sh && chmod +x /etc/cron.d/project_env.sh && crontab /etc/cron.d/artisan-schedule-run && cron && tail -f /var/log/cron.log"]
    env_file:
        - docker-compose.env
  worker:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    command: ["php", "artisan", "queue:work"]
    env_file:
      - docker-compose.env
  nginx:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-nginx
    ports:
      - "80"
      - "443"
    depends_on:
      - app
    links:
      - app
  mysql:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: tenancy
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: tenancy
    env_file:
        - docker-compose.env
  redis:
    container_name: redis
    image: redis
    links:
      - app

volumes:
  dbdata:
    driver: local